learning_users/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^register/', views.register, name = 'register'),
    url(r'user_login/', views.user_login, name='login'),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name = 'index'),
    url(r'^basic_app/', include('basic_app.urls')),
    url(r'^logout/', views.user_logout, name='logout'),
    url(r'^special/', views.special, name='special'),
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    portfolio = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from basic_app.models import UserModel
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta():
        model = UserModel
        fields = ('portfolio', 'profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
# Create your views here.

def index(request):
    return render(request, 'basic_app/index.html')

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()


            profile = profile_form.save(commit=False)
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.user = user
            profile.save()

            registered = True

        else:
            print('User form errors:',user_form.errors,'\nProfile form errors:', profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'basic_app/registration.html', {'registered': registered, 'user_form': user_form, 'profile_form': profile_form})

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            
            else:
                return HttpResponse('User is not active!')

        else:
            print('Login failed with username', username, 'password', password)
            return HttpResponse('Invalid Credentials')

    else:
        return render(request, 'basic_app/login.html', {})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
    
@login_required
def special(request):
    return HttpResponse('You have logged in!')

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">HOME</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">ADMIN</a></li>
                <li><a class="navbar-link" href="{% url 'basic_app:register' %}">REGISTER</a></li>

                {% if user.is_authenticated %}
                <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'basic_app:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block body_block %}

        {% endblock %}
    </div>
    
</body>
</html>

learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html" %}

{% block body_block %}

<div class="jumbotron">
    <h1>This is the home page</h1>
</div>

{% endblock %}

learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1>Login here!</h1>
    <form action="{% url 'basic_app:user_login' %" method="POST">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter username here">

        <label for="password">Password:</label>
        <input type="password" name="password" placeholder="Enter password here">

        <input type="submit" value="Login">
    </form>

</div>


{% endblock %}

learning_users/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load static %}


{% block body_block %}
    <div class="jumbotron">
        {% if registered %}
            <H1>Thank you for registering!</H1>
        {% else %}
            <H1>Register here!</H1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" value="Register" class="btn btn-primary">
            </form>
        {% endif %}
    </div>
{% endblock %}